music.play(music.stringPlayable("C5 C5 C5 C5 C5 C5 C5 C5 ", 120), music.PlaybackMode.InBackground)
basic.showNumber(20)
basic.showNumber(19)
basic.showNumber(18)
basic.showNumber(17)
basic.showNumber(16)
basic.showNumber(15)
basic.showNumber(14)
basic.showNumber(13)
basic.showNumber(12)
basic.showNumber(11)
basic.showNumber(10)
basic.showNumber(9)
basic.showNumber(8)
basic.showNumber(7)
basic.showNumber(6)
basic.showNumber(5)
basic.showNumber(4)
music.play(music.stringPlayable("A A A A A A A A ", 120), music.PlaybackMode.InBackground)
basic.showNumber(3)
basic.showNumber(2)
basic.showNumber(1)
basic.showNumber(0)
music.play(music.stringPlayable("G G G G G G G G ", 120), music.PlaybackMode.InBackground)
basic.showArrow(ArrowNames.North)
basic.forever(function () {
	
})
